version: '3'

services:
  composer:
    image: composer:2.5
    volumes:
      - .:/var/www:rw
    working_dir: /var/www
  http:
    image: caddy
    ports:
      - "8080:8080"
      - "443:443"
    volumes:
      - .:/var/www
      - ./Caddyfile:/etc/caddy/Caddyfile
  php:
    build:
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www:rw
      ###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
